Repository muesli/termenv, pull requests merged in 2022-01, with the labels that each got.

#51 termenv: add shim for js
  termenv_js.go
Labels: enhancement

#52 Don't run OSC queries on CI
  termenv.go
Labels: bug

#53 Add session commands
  README.md
  screen.go
  termenv.go
Labels: enhancement

#54 Add terminal compatbility list to README
  README.md
  ansi_compat.md
Labels: documentation

#55 Group vte-based terminals in README
  README.md
Labels: documentation

#56 Correctly parse COLORFGBG with three values
  termenv_unix.go
Labels: bug

#59 Add footnote about terminal multiplexers
  README.md
Labels: documentation

#58 Add 'kitty' and 'ansi' values as a fallback color support detection
  termenv_unix.go
Labels: enhancement

#61 Add helper to enable virtual terminal processing on Windows
  README.md
  termenv_windows.go
Labels: enhancement
